# Copyright (c) 2013, Toradex AG. All rights reserved.
# Copyright (c) 2013, NVIDIA CORPORATION.  All rights reserved.
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
# 1. The origin of this software must not be misrepresented; you must not
#    claim that you wrote the original software. If you use this software
#    in a product, an acknowledgment in the product documentation would be
#    appreciated but is not required.
# 2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
# 3. This notice may not be removed or altered from any source distribution.

include ../../../build/pre.mk

soc := t30

bcts := \
	colibri_t30_12MHz_1GB_NT5CC256M16CP-DI_400MHz-shmoo.bct

images := \
	colibri_t30.img

include ../../../build/post.mk
